// flow-typed signature: 70b928e506a01d6d117c51b3e3c23409
// flow-typed version: <<STUB>>/es2015_v0.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'es2015'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'es2015' {
  declare module.exports: any;
}
