// flow-typed signature: 87814b58078aabe62310f92c4f2a4f8b
// flow-typed version: <<STUB>>/express-routes-versioning_v^1.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-routes-versioning'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-routes-versioning' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-routes-versioning/examples/example1' {
  declare module.exports: any;
}

declare module 'express-routes-versioning/examples/example2' {
  declare module.exports: any;
}

declare module 'express-routes-versioning/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-routes-versioning/examples/example1.js' {
  declare module.exports: $Exports<'express-routes-versioning/examples/example1'>;
}
declare module 'express-routes-versioning/examples/example2.js' {
  declare module.exports: $Exports<'express-routes-versioning/examples/example2'>;
}
declare module 'express-routes-versioning/index' {
  declare module.exports: $Exports<'express-routes-versioning'>;
}
declare module 'express-routes-versioning/index.js' {
  declare module.exports: $Exports<'express-routes-versioning'>;
}
declare module 'express-routes-versioning/test/test.js' {
  declare module.exports: $Exports<'express-routes-versioning/test/test'>;
}
