// flow-typed signature: 67bfb423b1632c2be0b65b11361357ca
// flow-typed version: <<STUB>>/parallelshell_v^3.0.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parallelshell'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parallelshell' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'parallelshell/index' {
  declare module.exports: $Exports<'parallelshell'>;
}
declare module 'parallelshell/index.js' {
  declare module.exports: $Exports<'parallelshell'>;
}
