// flow-typed signature: d57a0a751a441b7bf24022cb2ae28469
// flow-typed version: <<STUB>>/routr_v^2.1.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'routr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'routr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'routr/lib/router' {
  declare module.exports: any;
}

// Filename aliases
declare module 'routr/index' {
  declare module.exports: $Exports<'routr'>;
}
declare module 'routr/index.js' {
  declare module.exports: $Exports<'routr'>;
}
declare module 'routr/lib/router.js' {
  declare module.exports: $Exports<'routr/lib/router'>;
}
