// flow-typed signature: aaed436438de1c0da17c0d18de24360a
// flow-typed version: <<STUB>>/v8flags_v^3.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'v8flags'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'v8flags' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'v8flags/config-path' {
  declare module.exports: any;
}

// Filename aliases
declare module 'v8flags/config-path.js' {
  declare module.exports: $Exports<'v8flags/config-path'>;
}
declare module 'v8flags/index' {
  declare module.exports: $Exports<'v8flags'>;
}
declare module 'v8flags/index.js' {
  declare module.exports: $Exports<'v8flags'>;
}
